on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: raubreywhite/rwtemplate/.github/workflows/r-package.yml@d80a0aa433cebe4968f2c52604ce04a7bf436439
