on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: raubreywhite/rwtemplate/.github/workflows/r-package.yml@6f9d23fd8d64edac64cf4fdcf93eb297b1914617
